# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3.8'
# docker-compose -f environment-docker-compose.yml up -d

services:
  chatgpt-data-app:
    image: glfs/chatgpt-data-app:1.1
    container_name: chatgpt-data-app
    ports:
      - "8090:8090"
    environment:
      - TZ=PRC
      - SERVER_PORT=8090
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - THREAD_POOL_EXECUTOR_CONFIG_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_CONFIG_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_CONFIG_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_CONFIG_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_CONFIG_POLICY=CallerRunsPolicy
      - CHATGPT_SDK_CONFIG_API_HOST=https://pro-share-api.zcyai.com/
      - CHATGPT_SDK_CONFIG_API_KEY=sk-x1J6vfuoi5FiBF3y2d8e8fB4E8B94f189140A962D0C0B9Ed
      - WX_CONFIG_ORIGINALID=gh_95eaac3ea5d1
      - WX_CONFIG_APPID=wx861d0c8b6e7eb1b8
      - WX_CONFIG_TOKEN=6666
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  chatgpt-web:
    container_name: chatgpt-web
    image: glfs/chatgpt-web:1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST_URL=http://localhost:8090
    restart: always